server:
   port: 8080
   servlet:
     context-path: /department-system
 
 spring:
   datasource:
     url: 'jdbc:mysql://localhost:3306/tagashira'
     driverClassName: 'com.mysql.cj.jdbc.Driver'
     username: root
     password: root
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true